name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Test if condition
      if: ${{ matrix.python }} == '3.7'
      run:
        echo ${{ matrix.python }}

    - name: Exit early
      run:
        exit 1

    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('dev-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python }}

    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Lint
      run: |
        flake8 -v
        black -v --check .

    - name: Type check
      run: |
        mypy allennlp_models --ignore-missing-imports --no-strict-optional --no-site-packages

    - name: Run tests
      run: |
        pytest --cov=allennlp_models/ --cov-report=xml

    - name: Upload coverage to Codecov
      if: ${{ matrix.python }} == '3.7'
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
